### ISSUE TITLE
Update flatpak

### ISSUE THREAD

**Issue by joereynolds** [daa84/neovim-gtk-flatpak#3]
The last release was in October, is there a way we can get a newer version? Perhaps even build the image when you push up to your other repo?

**Comment by daa84** [comment]
Is there any 'howto' on how to easily do this? or maybe example?

**Comment by joereynolds** [comment]
Hey @daa84, I'm not too sure.
An easy way might be to put the commands that you use to make the flatpak image into a shell script. Then have a git hook on your neovim-gtk repository that runs that shellscript. It's not as sophisticated as an automated build but it's better than manually creating it yourself
