### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by qazip** [daa84/neovim-gtk-flatpak#4]
In the README, you tell us how to run neovim-gtk via flatpak, but not how to install. 

Do you mind teling me how one is supposed to install neovim-gtk using flatpak?

**Comment by daa84** [comment]
`flatpak install nvim-gtk_x86_64.flatpak`
or
`flatpak install --user nvim-gtk_x86_64.flatpak` to install for current user only.

**Comment by qazip** [comment]
Well yes, I had tried that. Doesn't work:

```
Required runtime for org.daa.NeovimGtk/x86_64/master (org.gnome.Platform/x86_64/3.24) is not installed, searching...
The required runtime org.gnome.Platform/x86_64/3.24 was not found in a configured remote.
error: The Application org.daa.NeovimGtk/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.24 which is not installed
```

**Comment by qazip** [comment]
It finally worked. I suggest you add that to the readme.
